### PR TITLE
Used GrantPermissionRule instead of AndroidManifest.xml and requestLe…

### PR DESCRIPTION
**Pull request by siarhei-luskanau**
…gacyExternalStorage="true"

### CODE REVIEW

**Comment by justasm** [comment]
Hi, thank you for your contribution!

Good catch that the `androidTest/../AndroidManifest.xml` was a. misplaced and b. likely superfluous given the base manifest declares the same permissions and flags.

It's not clear to me whether the `GrantPermissionRule` is necessary given the screenshot tests were working previously. Did you run into some specific issue that this change fixed for you? How did you test this change?

**Comment by siarhei-luskanau** [comment]
>How did you test this change?
I have tested this changes by running `executeScreenshotTests` gradle task.

**Comment by siarhei-luskanau** [comment]
I saw the next log in logcat:
`java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
        at java.io.File.createNewFile(File.java:1008)
        at com.karumi.shot.compose.ScreenshotSaver.createFileIfNotExists(ScreenshotSaver.kt:105)
        at com.karumi.shot.compose.ScreenshotSaver.saveScreenshotBitmap(ScreenshotSaver.kt:77)
        at com.karumi.shot.compose.ScreenshotSaver.saveScreenshot(ScreenshotSaver.kt:31)
        at com.karumi.shot.compose.ComposeScreenshot.saveScreenshot(ComposeScreenshot.kt:21)
        at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot(ScreenshotTest.kt:135)
        at com.trafi.example.PreviewTest.compareScreenshot(PreviewTest.kt:7)
        at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot(ScreenshotTest.kt:114)
        at com.trafi.example.PreviewTest.compareScreenshot(PreviewTest.kt:7)
        at com.trafi.example.PreviewTest.renderAndTestView(PreviewTest.kt:10)`

I think that problem was in storage permissions.
I have tried to locate `androidTest/../AndroidManifest.xml` to another places and it wasn't successful.
I have added storage permissions via `GrantPermissionRule` and now `executeScreenshotTests` gradle task makes and compares screenshots.

**Comment by justasm** [comment]
Thanks, I've tested it too and it seems to work as expected 👍

**Review by justasm — APPROVED** [review]

**Pull request merged**
