### PR TITLE
Compose 1.0.0-rc02 & AGP 7.0.0-beta05

### PR DESCRIPTION
**Pull request by justasm**
Currently, `@Preview` is broken [due to this known issue](https://issuetracker.google.com/issues/192570889).

### CODE REVIEW

**Comment by siarhei-luskanau** [comment]
@justasm  Looks like need to add dependencies to the `android/ui-android/build.gradle.kts` to start androidTest successfully

    androidTestImplementation("androidx.compose.ui:ui-test-junit4:${Versions.compose}")
    androidTestImplementation("androidx.compose.ui:ui-test-manifest:${Versions.compose}")

**Comment by justasm** [comment]
@siarhei-luskanau thanks for the hint, will try locally

**Comment by justasm** [comment]
I've been exploring why the Android screenshot tests keep failing, and it seems like it may be an issue in the emulator runner action itself https://github.com/ReactiveCircus/android-emulator-runner/issues/168. Locally everything seems to work fine.

**Comment by siarhei-luskanau** [comment]
@justasm  Please try the latest version (v2.19.1) of Android Emulator Runner. It should fix `android_tests.yml` action.
https://github.com/ReactiveCircus/android-emulator-runner/releases/tag/v2.19.1

**Pull request merged**
